# Generated by Django 5.1 on 2025-08-13 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('jantina', models.CharField(choices=[('Lelaki', 'Lelaki'), ('Perempuan', 'Perempuan')], max_length=20)),
                ('bangsa', models.CharField(choices=[('Melayu', 'Melayu'), ('India', 'India'), ('Cina', 'Cina'), ('Lain-lain', 'Lain-lain')], max_length=20)),
                ('umur', models.CharField(choices=[('18 - 25 tahun', '18 - 25 tahun'), ('26 - 39 tahun', '26 - 39 tahun'), ('40 - 59 tahun', '40 - 59 tahun'), ('60 dan ke atas', '60 dan ke atas')], max_length=30)),
                ('job', models.CharField(choices=[('Ahli Majlis, MBI', 'Ahli Majlis, MBI'), ('Kakitangan MBI', 'Kakitangan MBI'), ('Kakitangan Kerajaan', 'Kakitangan Kerajaan'), ('Kakitangan Swasta', 'Kakitangan Swasta'), ('Bekerja Sendiri', 'Bekerja Sendiri'), ('Tidak Bekerja', 'Tidak Bekerja'), ('Pelajar', 'Pelajar'), ('Pesara', 'Pesara')], max_length=50)),
                ('zon', models.CharField(blank=True, choices=[('Zon 1', 'Zon 1'), ('Zon 2', 'Zon 2'), ('Zon 3', 'Zon 3'), ('Zon 4', 'Zon 4'), ('Zon 5', 'Zon 5'), ('Zon 6', 'Zon 6'), ('Zon 7', 'Zon 7'), ('Zon 8', 'Zon 8'), ('Zon 9', 'Zon 9'), ('Zon 10', 'Zon 10'), ('Zon 11', 'Zon 11'), ('Zon 12', 'Zon 12'), ('Zon 13', 'Zon 13'), ('Zon 14', 'Zon 14'), ('Zon 15', 'Zon 15'), ('Zon 16', 'Zon 16'), ('Zon 17', 'Zon 17'), ('Zon 18', 'Zon 18'), ('Zon 19', 'Zon 19'), ('Zon 20', 'Zon 20'), ('Zon 21', 'Zon 21'), ('Zon 22', 'Zon 22'), ('Zon 23', 'Zon 23'), ('Zon 24', 'Zon 24')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElemenUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemen', models.PositiveSmallIntegerField(choices=[(1, 'IPOH BANDAR TERBERSIH'), (2, 'KEMUDAHAN AWAM DAN TAMAN'), (3, 'KEMUDAHAN INFRASTRUKTUR'), (4, 'BANGUNAN DAN HARTANAH MAJLIS'), (5, 'HARTA MODAL (ASET)'), (6, 'IPOH BANDAR (BANDAR PINTAR)'), (7, 'IPOH BANDAR (BANDAR RENDAH KARBON)'), (8, 'PEMBANGUNAN EKONOMI MASYARAKAT DAN PELANCONGAN')])),
                ('pilihan', models.CharField(max_length=255)),
                ('lokasi', models.CharField(max_length=255)),
                ('butiran', models.TextField()),
                ('demografik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keutamaan', to='userideabajet.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Cadangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cad', models.TextField(blank=True, max_length=100000, null=True)),
                ('demografik', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cadangan', to='userideabajet.userinfo')),
            ],
        ),
    ]
