# Generated by Django 5.1 on 2025-08-13 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen1',
            fields=[
                ('e1id', models.AutoField(primary_key=True, serialize=False)),
                ('e1', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen2',
            fields=[
                ('e2id', models.AutoField(primary_key=True, serialize=False)),
                ('e2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen3',
            fields=[
                ('e3id', models.AutoField(primary_key=True, serialize=False)),
                ('e3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen4',
            fields=[
                ('e4id', models.AutoField(primary_key=True, serialize=False)),
                ('e4', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen5',
            fields=[
                ('e5id', models.AutoField(primary_key=True, serialize=False)),
                ('e5', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen6',
            fields=[
                ('e6id', models.AutoField(primary_key=True, serialize=False)),
                ('e6', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen7',
            fields=[
                ('e7id', models.AutoField(primary_key=True, serialize=False)),
                ('e7', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Elemen8',
            fields=[
                ('e8id', models.AutoField(primary_key=True, serialize=False)),
                ('e8', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('list_lokasi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Aset',
            fields=[
                ('asetid', models.AutoField(primary_key=True, serialize=False)),
                ('list_aset', models.CharField(max_length=255)),
                ('elemen5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminideabajet.elemen5')),
            ],
        ),
    ]
